"""
Audit Log Model (Pillar 3 - Event Tracking)
=============================================
This file defines the AuditLog SQLAlchemy model.

You should implement here:
- AuditLog class inheriting from Base
- Fields: id (UUID), action (str, e.g., "task_created", "status_changed"),
  entity_type (str), entity_id (UUID), details (JSON/dict),
  organization_id (FK), performed_by (FK to users, nullable for system actions),
  created_at (datetime)

Audit logs are generated by:
- Background tasks triggered by webhook events
- AI agent actions (when a tool creates/modifies data)
- Any significant state change in the system
"""
